### ISSUE TITLE
Add azerty support for french users

### ISSUE THREAD

**Issue by plecavelier** [bjeavons/zxcvbn-php#51]
Modify spatial match to support azerty keyboard for french users

**Comment by mkopinsky** [comment]
Thanks for the issue and PR!

In general, our goals with this repo is to maintain feature parity with the upstream (dropbox/zxcvbn). https://github.com/dropbox/zxcvbn/issues/190 is the feature request in the upstream for azerty support.

This was discussed previously in https://github.com/mkopinsky/zxcvbn-php/pull/8 (before my fork was merged back into this repo).

It's really a shame that the upstream project seems to be abandoned - I wish there were a single community fork that people could gravitate to and that supported things that people are asking for (support for azerty or other keyboards, smaller bundle size, perhaps typescript instead of coffeescript, etc.). Unfortunately I'm personally not in a position right now to try to make that happen - too much going on in life.
