### ISSUE TITLE
Target class [App\Http\Livewire\ZxcvbnPhp\Zxcvbn] does not exist.

### ISSUE THREAD

**Issue by devhoussam** [bjeavons/zxcvbn-php#53]
I'm trying to using `ZxcvbnPhp\Zxcvbn` in my livewire component I installed the all requirements but it get me this error : 

`Target class [App\Http\Livewire\ZxcvbnPhp\Zxcvbn] does not exist.`

**Comment by mkopinsky** [comment]
This isn't something I can really debug without seeing your full code, and this isn't really the place for that - I'd ask in a Laravel forum or the like about how to reference external libraries from livewire.

This seems like it's trying to reference the class relative to the current class, rather than relative to root namespace. Might be as simple as using `\ZxcvbnPhp\Zxcvbn` instead of `ZxcvbnPhp\Zxcvbn`.
