### ISSUE TITLE
[1.4.0] SpacialMatch final

### ISSUE THREAD

**Issue by tminich** [bjeavons/zxcvbn-php#82]
Is there a particular reason SpacialMatch was made final? I was extending the class to check for the German qwertz keyboard layout.

I'm open for better solutions, extending SpacialMatch seemed like a good one to add additional keyboard layouts.

**Comment by mkopinsky** [comment]
Extending SpatialMatch sounds reasonable. I made it static to appease phpstan about `Unsafe usage of new static()`. There are other solutions I could do:
1. constructing a `new SpatialMatch` instead of `new static` in `\ZxcvbnPhp\Matchers\SpatialMatch::match` (I'm guessing this wouldn't work for you - you probably need this to instantiate a new GermanSpatialMatch or whatever your subclass is)
2. Making the constructor private. This messes with unit tests
3. Ignore the phpstan errors
4. Use `/** @phpstan-consistent-constructor */` to silence the errors. This is what I'm leaning towards

**Comment by mkopinsky** [comment]
Fixed in 2761732e28920a6bcc32339d213c957b149ed587
